// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabzBmkxlZsX39mNL8ZG5d8jeY4AzC_x0',
    appId: '1:1056460985345:web:fb743289d2ad4b84cddc00',
    messagingSenderId: '1056460985345',
    projectId: 'hertwin-wellness',
    authDomain: 'hertwin-wellness.firebaseapp.com',
    storageBucket: 'hertwin-wellness.firebasestorage.app',
    measurementId: 'G-GYEJKR9LRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8_xh48Ve0dDWoVExi8dFK6yd3XqamkZ0',
    appId: '1:1056460985345:android:9d87cb5ad7d6dceecddc00',
    messagingSenderId: '1056460985345',
    projectId: 'hertwin-wellness',
    storageBucket: 'hertwin-wellness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiWfJOOzf0Zt90WFOe5A-bTzVop1877dc',
    appId: '1:1056460985345:ios:862795ab172d6b91cddc00',
    messagingSenderId: '1056460985345',
    projectId: 'hertwin-wellness',
    storageBucket: 'hertwin-wellness.firebasestorage.app',
    iosBundleId: 'com.mycompany.hertwinwellness',
  );
}
