#!/usr/bin/env bash
#
# Creates the Play Store upload keystore and wires it into the Gradle build.
#
# Run this yourself. keytool prompts for the password interactively and it is
# never passed as an argument, never echoed, and never written anywhere except
# android/key.properties (which is gitignored). Nobody else needs to see it.
#
#   bash tool/create-keystore.sh
#
set -euo pipefail

JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@17}"
KEYTOOL="$JAVA_HOME/bin/keytool"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE_DIR="$HOME/.android-keystores"
KEYSTORE="$KEYSTORE_DIR/hertwin-upload.jks"
ALIAS="upload"
PROPS="$REPO_ROOT/android/key.properties"

if [ ! -x "$KEYTOOL" ]; then
  echo "keytool not found at $KEYTOOL"
  echo "Set JAVA_HOME to your JDK 17 install and re-run."
  exit 1
fi

if [ -f "$KEYSTORE" ]; then
  echo "A keystore already exists at:"
  echo "  $KEYSTORE"
  echo
  echo "Refusing to overwrite it. If you overwrite the key your app was"
  echo "published with, Google Play will reject every future update."
  echo "Delete it manually only if you are certain it was never used."
  exit 1
fi

# Deliberately outside the repo, so no git operation can ever pick it up.
mkdir -p "$KEYSTORE_DIR"
chmod 700 "$KEYSTORE_DIR"

cat <<'INTRO'
────────────────────────────────────────────────────────────────────────
Creating your Play Store upload key.

You will be asked for:
  • a keystore password (choose a strong one, twice)
  • your name / organisation / city / country  (these appear in the
    certificate; "HerTwin" and your city are fine)

Nothing you type here is logged or sent anywhere.

AFTERWARDS, BACK THE KEYSTORE FILE UP. If you lose it you can never
update your own app — you would have to republish under a new package
name and every user would have to reinstall.
────────────────────────────────────────────────────────────────────────
INTRO

"$KEYTOOL" -genkeypair -v \
  -keystore "$KEYSTORE" \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000

chmod 600 "$KEYSTORE"

echo
echo "Keystore created: $KEYSTORE"
echo
echo "Now writing android/key.properties so Gradle can find it."
echo "Enter the SAME keystore password you just chose:"

# -s: no echo. Read straight into the file; never printed, never in argv.
read -rsp "  keystore password: " STORE_PASS
echo
read -rsp "  key password (press Enter if same): " KEY_PASS
echo
KEY_PASS="${KEY_PASS:-$STORE_PASS}"

umask 077
cat > "$PROPS" <<EOF
# Generated by tool/create-keystore.sh — gitignored, never commit this.
storeFile=$KEYSTORE
storePassword=$STORE_PASS
keyPassword=$KEY_PASS
keyAlias=$ALIAS
EOF
chmod 600 "$PROPS"

unset STORE_PASS KEY_PASS

echo
echo "Wrote $PROPS (permissions 600)."
echo
echo "Verifying it is ignored by git…"
if git -C "$REPO_ROOT" check-ignore -q android/key.properties; then
  echo "  ✓ android/key.properties is gitignored"
else
  echo "  ✗ WARNING: key.properties is NOT gitignored. Fix before committing."
  exit 1
fi

echo
echo "Done. Build a signed bundle with:"
echo "  flutter build appbundle --release --no-tree-shake-icons"
echo
echo "Confirm it is NOT debug-signed:"
echo "  \$ANDROID_HOME/build-tools/36.0.0/apksigner verify --print-certs \\"
echo "      build/app/outputs/flutter-apk/app-release.apk"
